### ISSUE TITLE
Annotation to protect certain resources from updates.

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#11]
When object has this annotation, do not make any changes to it. 
Create also log message if such object would have been changed by update, but was not - to prevent confusion "why is this not updating????"
```
metadata:
  name: ...
  annotations:
    entigo-k8s-gitops/protected: true
```
