### ISSUE TITLE
Make sure all of the following objects are supported under update command

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#12]
Object kinds are as follows:

Deployment
```
spec:
  template:
    spec:
      containers:
```
Statefulset
```
spec:
  template:
    spec:
      containers:
```
CronJob
```
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
```
Job
```
spec:
  template:
    spec:
      containers:
```
Daemonset
```
spec:
  template:
    spec:
      containers:
```
Pod
```
spec:
  containers:
```
