### ISSUE TITLE
Update command should support init containers

### ISSUE THREAD

**Issue by kertkukk** [entigolabs/entigo-k8s-gitops#14]
@priitr-ent suggested that update command should support [Init Containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)

(Related to #12)

**Comment by martivo** [comment]
He is right.

**Comment by martivo** [comment]
Deployment
```
spec:
  template:
    spec:
      initContainers:
```
Statefulset
```
spec:
  template:
    spec:
      initContainers:
```
CronJob
```
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
```
Job
```
spec:
  template:
    spec:
      initContainers:
```
Daemonset
```
spec:
  template:
    spec:
      initContainers:
```
Pod
```
spec:
  initContainers:
```
